learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
'''learning_logsのURLパターン定義'''

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # ホームページ
    path('', views.index, name='index'),
    # トピック一覧
    path('topics/', views.topics, name='topics'),
    # 個別トピックのページ
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 新規トピック追加ページ
    path('new_topic/', views.new_topic, name='new_topic'),
    # 新規記事追加ページ
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # 記事の編集ページ
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    # 記事の削除
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
]

users/urls.py
'''users用URLパターン'''

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # デフォルトの認証URLを取り込む
    path('', include('django.contrib.auth.urls')),
    # ユーザー登録ページ
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """ユーザーが学んでいるトピックを表す"""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    """モデルの文字列表現を返す"""

    def __str__(self):
        return self.text


class Entry(models.Model):
    """トピックに関して学んだ具体的なこと"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'entries'

    """モデルの文字列表現を返す"""

    def __str__(self):
        # テキストが25文字を超えた場合は、省略記号を付与する
        return f'{self.text[:25]}...' if len(self.text) > 25 else self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


# 新規トピックを追加するフォームクラス
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


# 新規記事を追加するフォームクラス
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# ホームページ
def index(request):
    '''学習ノートのホームページ'''
    return render(request, "learning_logs/index.html")


# トピック一覧
@login_required
def topics(request):
    '''すべてのトピックを表示する'''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, "learning_logs/topics.html", context)


# 個別トピックのページ
@login_required
def topic(request, topic_id):
    '''トピックの全ての記事を表示'''
    topic = Topic.objects.get(id=topic_id)

    # トピックが現在のユーザーが所持するものであることを確認する
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, "learning_logs/topic.html", context)


# 新規トピック追加ページ（フォーム）
@login_required
def new_topic(request):
    # 新規トピックの追加
    if request.method != 'POST':
        # データ送信されていない場合、空のフォームを生成
        form = TopicForm()
    else:
        # データ送信された場合
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # 空のフォームを表示
    context = {'form': form}
    return render(request, "learning_logs/new_topic.html", context)


# 新規記事追加ページ（フォーム）
@login_required
def new_entry(request, topic_id):
    '''特定のトピックに新規記事を追加する'''
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # データ送信されていない場合、空のフォームを生成
        form = EntryForm()
    else:
        # データ送信された場合
        form = EntryForm(data=request.POST)  # EntryFormクラスをインスタンス化
        if form.is_valid():
            new_entry = form.save(commit=False)  # Entryクラス（モデル）をインスタンス化
            new_entry.topic = topic  # 生成したEntryのインスタンスにtopicを代入。
            new_entry.save()  # DBに保存（テーブルにインサート）
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


# 記事の編集ページ
@login_required
def edit_entry(request, entry_id):
    '''既存の記事を編集する'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # トピックが現在のユーザーが所持するものであることを確認する
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初回リクエスト時は現在の記事の内容がフォームに埋め込まれている
        form = EntryForm(instance=entry)
    else:
        # POSTでデータが送信されたとき（編集時）
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


# 記事の削除
@login_required
def delete_entry(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)

    if request.method == 'POST':
        entry.delete()
        return redirect('learning_logs:topic', topic_id=entry.topic.id)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    '''新しいユーザーを登録する'''
    if request.method != 'POST':
        # 空のユーザー登録フォームを表示する
        form = UserCreationForm()
    else:
        # 入力済みのフォームを処理する
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # ユーザーをログインさせてホームページにリダイレクトする
            login(request, new_user)
            return redirect('learning_logs:index')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>学習ノート</title>
        <meta name="description" content="学習ノートアプリ。トピックや記事を管理して学習を記録できます。">
        <meta name="keywords" content="Python, Django, 学習ノート, Webアプリ">
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border pe-3">
            <a class="navbar-brand ms-3" href="{% url "learning_logs:index" %}">学習ノート</a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active"
                           aria-current="page"
                           href="{% url "learning_logs:topics" %}">トピック一覧</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text me-3">こんにちは{{ user.username }}さん</span>
                        </li>
                        <li class="nav-item">
                            <form class="d-inline" action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <a href="#" onclick="this.closest('form').submit(); return false;">ログアウト</a>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href={% url "users:register" %}>ユーザー登録</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={% url "users:login" %}>ログイン</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}
                {% endblock page_header %}
            </div>
            <div>
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>記事を編集：</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>記事を編集</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "base.html" %}
{% block page_header %}
  <div class="p-5 mb-4 bg-light text-dark rounded-3">
    <h1 class="display-3">学んだことを記録しよう</h1>
    <p class="lead">
      自分だけの学習ノートを作成して、学んだことをいつでも振り返れるようにしよう。
      <br>
      何か新しいことを学んだら、その内容を要約した記事を書こう。
    </p>
    <a class="btn btn-lg btn-primary"
       href="{% url "users:register" %}"
       role="button">登録する &raquo;</a>
  </div>
{% endblock page_header %}
{% block content %}
  <p>学習ノートを使えば、好みのトピックについて学習していることを記録して、いつも最新の状態をハックできます。</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>新しい記事を追加</p>
    <form action={% url "learning_logs:new_entry" topic.id %} method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>記事を追加</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "base.html" %}
{% block content %}
    <p>新規トピックを追加：</p>
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>トピックを追加</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "base.html" %}
{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">新しい記事を追加</a>
    </p>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'Y年m月d日 h:i' }}
                <small><a href={% url "learning_logs:edit_entry" entry.id %}>編集</a></small>
                <small>
                    <form class="d-inline"
                          method='post'
                          action="{% url "learning_logs:delete_entry" entry.id %}">
                        {% csrf_token %}
                        <a href="#"
                           onclick="if (confirm('本当に削除しますか？')) { this.closest('form').submit(); } return false;">削除</a>
                    </form>
                </small>
            </h4>
            <div class="card-body">{{ entry.text|linebreaks }}</div>
        </div>
    {% empty %}
        <p>このトピックにはまだ記事がありません</p>
    {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "base.html" %}
{% block page_header %}
    <h1>トピック一覧</h1>
{% endblock page_header %}
{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>
                <h3>トピックはまだ作成されていません</h3>
            </li>
        {% endfor %}
    </ul>
    <h3>
        <a href="{% url 'learning_logs:new_topic' %}">新規トピックを追加</a>
    </h3>
{% endblock content %}